import 'package:flutter/material.dart';

import 'mock_scenario_phase.dart';

class MockScenarioDefinition {
  const MockScenarioDefinition({
    required this.id,
    required this.title,
    required this.summary,
    required this.duration,
    required this.keyframes,
  });

  final String id;
  final String title;
  final String summary;
  final Duration duration;
  final List<MockScenarioKeyframe> keyframes;
}

class MockScenarioKeyframe {
  const MockScenarioKeyframe({
    required this.at,
    required this.phase,
    required this.userPosition,
    required this.stopPosition,
    required this.targetBusPosition,
    this.secondaryBusPosition,
    required this.busMoving,
    required this.busStopped,
    required this.geofenceArmed,
    required this.geofenceReleased,
    required this.geofenceRadius,
    required this.cueType,
    required this.message,
    required this.targetBusLabel,
    this.secondaryBusLabel,
    this.scriptLineId,
  });

  final Duration at;
  final MockScenarioPhase phase;
  final Offset userPosition;
  final Offset stopPosition;
  final Offset targetBusPosition;
  final Offset? secondaryBusPosition;
  final bool busMoving;
  final bool busStopped;
  final bool geofenceArmed;
  final bool geofenceReleased;
  final double geofenceRadius;
  final String cueType;
  final String message;
  final String targetBusLabel;
  final String? secondaryBusLabel;
  final String? scriptLineId;
}

const _stop = Offset(0.50, 0.48);
const _wait = Offset(0.50, 0.76);
const _radius = 0.32;

const List<MockScenarioDefinition> mockScenarioDefinitions =
    <MockScenarioDefinition>[
  MockScenarioDefinition(
    id: 's01_left_approach_board',
    title: '시나리오 1: 왼쪽 접근 후 탑승',
    summary: '목표 버스가 왼쪽에서 들어와 정차하고 사용자가 문 방향으로 이동해 탑승합니다.',
    duration: Duration(milliseconds: 24600),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.04, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '정류장 안전 구역에 도착했습니다. 왼쪽에서 목표 버스가 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'scenario_01_start',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 6144),
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.36, 0.34),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스가 왼쪽 전방에서 가까워지고 있습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_approaching',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 10704),
        phase: MockScenarioPhase.busStopped,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스가 정차했습니다. 출입문은 오른쪽 앞 방향입니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_stopped',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 16176),
        phase: MockScenarioPhase.boardingPrompt,
        userPosition: Offset(0.548, 0.56),
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '출입문 근처입니다. 천천히 탑승하세요.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarding_prompt',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 20376),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.548, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '탑승이 확인되었습니다. 안내를 종료합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's03_two_buses_select_target',
    title: '시나리오 2: 정류장에 버스 두 대',
    summary: '두 대가 이미 정차한 상태에서 비콘 거리와 노선 번호로 목표 버스를 고릅니다.',
    duration: Duration(milliseconds: 22872),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.busStopped,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        secondaryBusPosition: Offset(0.36, 0.37),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'warning',
        message: '정류장에 버스 두 대가 있습니다. 왼쪽 511번은 목표 버스가 아닙니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 다른 버스',
        scriptLineId: 'wrong_bus_warning',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 6600),
        phase: MockScenarioPhase.busStopped,
        userPosition: Offset(0.52, 0.66),
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        secondaryBusPosition: Offset(0.36, 0.37),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '오른쪽 앞 502번 버스가 목표입니다. 오른쪽 문 방향으로 이동합니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 다른 버스',
        scriptLineId: 'target_bus_confirmed',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 14760),
        phase: MockScenarioPhase.boardingPrompt,
        userPosition: Offset(0.556, 0.56),
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        secondaryBusPosition: Offset(0.36, 0.37),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스 출입문 앞입니다. 탑승하세요.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 다른 버스',
        scriptLineId: 'boarding_prompt',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 19200),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.556, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        secondaryBusPosition: Offset(0.36, 0.37),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '올바른 버스 탑승이 확인되었습니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 다른 버스',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's04_wrong_bus_first',
    title: '시나리오 3: 잘못된 버스 먼저 접근',
    summary: '다른 노선 버스가 먼저 가까워질 때 강한 경고 후 목표 버스를 다시 안내합니다.',
    duration: Duration(milliseconds: 27504),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.08, 0.30),
        secondaryBusPosition: Offset(0.30, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스는 아직 멀리 있습니다. 다른 버스가 왼쪽에서 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 접근 중',
        scriptLineId: 'scenario_04_start',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 6936),
        phase: MockScenarioPhase.wrongBusWarning,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.22, 0.32),
        secondaryBusPosition: Offset(0.50, 0.36),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'warning',
        message: '가까운 버스는 511번입니다. 목표 버스가 아니므로 탑승하지 마세요.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 잘못된 버스',
        scriptLineId: 'wrong_bus_warning',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 13320),
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.44, 0.34),
        secondaryBusPosition: Offset(0.80, 0.30),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 502번 버스가 왼쪽에서 다시 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '511번 통과',
        scriptLineId: 'bus_approaching',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 17472),
        phase: MockScenarioPhase.boardingPrompt,
        userPosition: Offset(0.54, 0.56),
        stopPosition: _stop,
        targetBusPosition: Offset(0.54, 0.444),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '이제 목표 버스가 정차했습니다. 출입문 방향으로 이동합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarding_prompt',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 23352),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.54, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.54, 0.444),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '잘못된 버스를 피하고 목표 버스에 탑승했습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's05_bus_passed_missed',
    title: '시나리오 4: 버스 놓침',
    summary: '목표 버스가 정차하지 않고 지나가면 missed cue와 다음 버스 안내를 보여줍니다.',
    duration: Duration(milliseconds: 24440),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.08, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스가 빠르게 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_approaching',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 5000),
        phase: MockScenarioPhase.busMovingLeftToRight,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.55, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '버스가 정류장 앞을 지나가고 있습니다. 아직 정차하지 않았습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'target_bus_moving',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 11072),
        phase: MockScenarioPhase.missedBus,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.95, 0.30),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'missed',
        message: '버스가 정차하지 않고 지나갔습니다. 다음 도착 정보를 안내합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'missed_bus',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 17456),
        phase: MockScenarioPhase.missedBus,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(1.08, 0.28),
        busMoving: false,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'none',
        message: '다음 502번 버스를 기다립니다. 안전 구역 안에 머물러 주세요.',
        targetBusLabel: '다음 502번 대기',
        scriptLineId: 'next_bus_wait',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's06_geofence_exit_return',
    title: '시나리오 5: 지오펜싱 무단 이탈',
    summary: '대기 중 사용자가 안전 구역을 벗어나면 경고 후 정류장으로 복귀합니다.',
    duration: Duration(milliseconds: 21440),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.20, 0.31),
        busMoving: false,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '정류장 안전 구역에서 버스를 기다립니다.',
        targetBusLabel: '502번 도착 예정',
        scriptLineId: 'arrive_at_stop',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 5000),
        phase: MockScenarioPhase.geofenceWarning,
        userPosition: Offset(0.80, 0.82),
        stopPosition: _stop,
        targetBusPosition: Offset(0.30, 0.31),
        busMoving: false,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'alarm',
        message: '안전 구역을 벗어났습니다. 정류장 방향으로 돌아오세요.',
        targetBusLabel: '502번 도착 예정',
        scriptLineId: 'geofence_warning',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 10184),
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.42, 0.31),
        busMoving: false,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '안전 구역 안으로 복귀했습니다. 다시 버스 접근을 안내합니다.',
        targetBusLabel: '502번 도착 예정',
        scriptLineId: 'return_to_geofence',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 15872),
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.56, 0.34),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스가 접근합니다. 안전 구역 안에서 대기하세요.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_approaching',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's07_danger_zone',
    title: '시나리오 6: 차도 위험 구역 접근',
    summary: '사용자가 차도 쪽으로 이동할 때 더 강한 위험 경고와 복귀 방향을 안내합니다.',
    duration: Duration(milliseconds: 19456),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.20, 0.30),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '정류장 대기 중입니다. 차도 방향 접근을 감시합니다.',
        targetBusLabel: '502번 접근 중',
        scriptLineId: 'arrive_at_stop',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 5616),
        phase: MockScenarioPhase.dangerWarning,
        userPosition: Offset(0.48, 0.40),
        stopPosition: _stop,
        targetBusPosition: Offset(0.36, 0.30),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'alarm',
        message: '차도에 가까워졌습니다. 뒤쪽 안전 보도 방향으로 이동하세요.',
        targetBusLabel: '502번 접근 중',
        scriptLineId: 'danger_zone',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 11880),
        phase: MockScenarioPhase.atStopGeofenceArmed,
        userPosition: Offset(0.50, 0.70),
        stopPosition: _stop,
        targetBusPosition: Offset(0.55, 0.34),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '안전 보도 쪽으로 복귀했습니다.',
        targetBusLabel: '502번 접근 중',
        scriptLineId: 'return_to_geofence',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 15880),
        phase: MockScenarioPhase.busStopped,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.552, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '목표 버스가 안전하게 정차했습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_stopped',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's08_beacon_signal_lost',
    title: '시나리오 7: 비콘 신호 끊김',
    summary: '목표 버스 접근 중 비콘 신호가 약해지면 시각 정보와 마지막 방향으로 보수 안내합니다.',
    duration: Duration(milliseconds: 22368),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.10, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '비콘 신호가 정상입니다. 목표 버스가 왼쪽에서 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_approaching',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 6696),
        phase: MockScenarioPhase.signalLost,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.46, 0.34),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'warning',
        message: '비콘 신호가 약해졌습니다. 마지막 확인 방향은 왼쪽 전방입니다.',
        targetBusLabel: '502번 신호 약함',
        scriptLineId: 'signal_lost',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 13584),
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.532, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '신호가 회복되었습니다. 목표 버스가 정차했습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'bus_stopped',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 18672),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.532, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.532, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '신호 복구 후 탑승 완료.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's09_crowded_obstacle',
    title: '시나리오 8: 혼잡/장애물 우회',
    summary: '정류장 앞 장애물 때문에 사용자 경로를 한 번 우회시킨 뒤 문 앞으로 안내합니다.',
    duration: Duration(milliseconds: 21416),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.busStopped,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        secondaryBusPosition: Offset(0.48, 0.56),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'warning',
        message: '출입문 앞이 혼잡합니다. 왼쪽으로 우회한 뒤 접근합니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '혼잡 구역',
        scriptLineId: 'obstacle_detected',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 6000),
        phase: MockScenarioPhase.userApproachingBus,
        userPosition: Offset(0.38, 0.62),
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        secondaryBusPosition: Offset(0.48, 0.56),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '혼잡 구역을 피해 왼쪽으로 우회 중입니다.',
        targetBusLabel: '502번 목표 버스',
        secondaryBusLabel: '혼잡 구역',
        scriptLineId: 'detour_left',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 12000),
        phase: MockScenarioPhase.boardingPrompt,
        userPosition: Offset(0.548, 0.56),
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '우회 완료. 출입문 앞입니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarding_prompt',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 17000),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.548, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.548, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '혼잡 구역을 피해 안전하게 탑승했습니다.',
        targetBusLabel: '502번 목표 버스',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
  MockScenarioDefinition(
    id: 's10_route_change_next_bus',
    title: '시나리오 9: 노선 변경/다음 버스 안내',
    summary: '선택 노선이 바뀌거나 목표 버스가 취소될 때 다음 적합 버스로 안내를 전환합니다.',
    duration: Duration(milliseconds: 27248),
    keyframes: <MockScenarioKeyframe>[
      MockScenarioKeyframe(
        at: Duration.zero,
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.18, 0.32),
        secondaryBusPosition: Offset(0.05, 0.33),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '기존 목표 버스 502번이 접근 중입니다.',
        targetBusLabel: '502번 기존 목표',
        secondaryBusLabel: '513번 후보',
        scriptLineId: 'bus_approaching',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 5000),
        phase: MockScenarioPhase.routeChanged,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.42, 0.33),
        secondaryBusPosition: Offset(0.22, 0.34),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'warning',
        message: '목적지 변경으로 513번이 더 적합합니다. 목표 버스를 전환합니다.',
        targetBusLabel: '502번 기존 목표',
        secondaryBusLabel: '513번 새 목표',
        scriptLineId: 'route_changed',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 11768),
        phase: MockScenarioPhase.busApproaching,
        userPosition: _wait,
        stopPosition: _stop,
        targetBusPosition: Offset(0.40, 0.34),
        secondaryBusPosition: Offset(0.85, 0.32),
        busMoving: true,
        busStopped: false,
        geofenceArmed: true,
        geofenceReleased: false,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '새 목표 513번 버스가 왼쪽에서 접근합니다.',
        targetBusLabel: '513번 새 목표',
        secondaryBusLabel: '502번 통과',
        scriptLineId: 'target_bus_confirmed',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 17216),
        phase: MockScenarioPhase.boardingPrompt,
        userPosition: Offset(0.556, 0.56),
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: true,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'normal',
        message: '513번이 정차했습니다. 새 목표 버스에 탑승하세요.',
        targetBusLabel: '513번 새 목표',
        scriptLineId: 'boarding_prompt',
      ),
      MockScenarioKeyframe(
        at: Duration(milliseconds: 23264),
        phase: MockScenarioPhase.boarded,
        userPosition: Offset(0.556, 0.5),
        stopPosition: _stop,
        targetBusPosition: Offset(0.556, 0.44),
        busMoving: false,
        busStopped: true,
        geofenceArmed: false,
        geofenceReleased: true,
        geofenceRadius: _radius,
        cueType: 'success',
        message: '변경된 목표 버스 탑승이 완료되었습니다.',
        targetBusLabel: '513번 새 목표',
        scriptLineId: 'boarded_success',
      ),
    ],
  ),
];
